version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqagittestProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SiqagittestProject
  gitUsername: siqagituser
  gitBranch: main
